### ISSUE TITLE
Recursive generation of uploaded artifact ids

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-server#28]
The template server should recursively auto-generate identifiers (@id) for resources embedded at levels of depth higher than one. 
Current implementation is enough to work from the front-end but it may be limited for users that need to use the REST services to create templates/elements with embedded elements/fields.

**Comment by martinjoconnor** [comment]
@marcosmro, I presume that this is still the case. How hard would it be to generate these identifiers recursively? We many not be conformant with the validation if we do not.

**Comment by martinjoconnor** [comment]
To clarify, the latest model assumes that templates, elements, and fields uploaded via the REST API have the following fields present with null values:

     "@id": null,
     "pav:createdOn": null,
     "pav:createdBy": null,
     "pav:lastUpdatedOn": null,
     "oslc:modifiedBy": null

The assumption is that the server will recursively fill in appropriate values for these fields.

What is the current behaviour for uploaded instances? Do we assume the same for template instances and element instances (not fields, because they are not represented as objects)?

**Comment by marcosmro** [comment]
For templates, elements, and fields, the server is currently filling in those fields. 

In the case of instances, those fields are only generated and filled in at the top level (template level). I think that the only remaining task here would be to to add and fill in those fields for element instances (related to metadatacenter/cedar-model-validation-library#21).

**Comment by martinjoconnor** [comment]
Great. I'll close this and let metadatacenter/cedar-model-validation-library#21 finalize it.
